/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ctrip.cmessaging.client.content;


import org.apache.thrift.TEnum;

public enum AckMode implements TEnum {
  Nack(0),
  Ack(1);

  private final int value;

  private AckMode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AckMode findByValue(int value) {
    switch (value) {
      case 0:
        return Nack;
      case 1:
        return Ack;
      default:
        return null;
    }
  }
}
