/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ctrip.cmessaging.client.content;


import org.apache.thrift.TEnum;

public enum CompressionType implements TEnum {
  None(0),
  GZip(1);

  private final int value;

  private CompressionType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CompressionType findByValue(int value) {
    switch (value) {
      case 0:
        return None;
      case 1:
        return GZip;
      default:
        return null;
    }
  }
}
