/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ctrip.cmessaging.client.content;


import org.apache.thrift.TEnum;

public enum MessageType implements TEnum {
  Text(1),
  Binary(2),
  Object(3);

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MessageType findByValue(int value) {
    switch (value) {
      case 1:
        return Text;
      case 2:
        return Binary;
      case 3:
        return Object;
      default:
        return null;
    }
  }
}
