/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ctrip.cmessaging.client.content;


import org.apache.thrift.TEnum;

public enum SerializationType implements TEnum {
  Thrift(0),
  Xml(1),
  Binary(2),
  Json(3),
  Protobuf(4);

  private final int value;

  private SerializationType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SerializationType findByValue(int value) {
    switch (value) {
      case 0:
        return Thrift;
      case 1:
        return Xml;
      case 2:
        return Binary;
      case 3:
        return Json;
      case 4:
        return Protobuf;
      default:
        return null;
    }
  }
}
